# This is a basic workflow to help you get started with Actions

name: Source Repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check Event Type
      id: check_event
      run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            title="${{ github.event.head_commit.message }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            title="${{ github.event.pull_request.title }}"
          else
            echo "This event is not supported."
            exit 1
          fi
          echo "Event Title: $title"
          echo "EVENT_TITLE_DESC=$title" >> $GITHUB_ENV
      
      # Get the current branch name and store in env variable
    - name: Get current branch
      run: |
          #Extract branch name from GITHUB_REF (e.g. 'refs/heads/<branch-name>')
          branch_name="${GITHUB_REF##*/}"
          echo "CRR_BR_NAME=$branch_name" >> $GITHUB_ENV
          echo "Current branch: $branch_name"
      
      # Send the Push or Pull event of current source repo branch to trigger the workflow of specific branch in remote repository 
    - name: Send Repository Event Workflow Dispatch
      env: 
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
      run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type":"My Custom Event","client_payload":{"title":"${{env.EVENT_TITLE_DESC}}"}}' \
          https://api.github.com/repos/rsenthilr/TestTargetRepo/dispatches
